---
project_name: pgbackrest_exporter

builds:
  - env: 
      - CGO_ENABLED=0
    goos: 
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: 
      - -trimpath
      - -mod=vendor
    ldflags: "-s -w -X main.version={{ .Version }}"
    main: .

archives:
  - id: pgbackrest_exporter
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    replacements:
      amd64: x86_64
      darwin: macos

nfpms:
  -
    id: pgbackrest_exporter
    package_name: pgbackrest_exporter
    builds:
      - pgbackrest_exporter
    replacements:
      amd64: x86_64
    homepage: https://github.com/woblerr/pgbackrest_exporter/
    maintainer: Anton Kurochkin <antkurochkin@gmail.com>
    description: Prometheus exporter for pgBackRest
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: pgbackrest_exporter.service.txt
        dst: /etc/systemd/system/pgbackrest_exporter.service

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

changelog:
  skip: true